name: Build and Upload to S3

on:
  pull_request:
    branches:
      - master # Executa apenas quando um PR for mesclado na branch master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Project
      run: mvn clean package

    - name: Package Lambda Code
      run: |
        mkdir -p target/lambda
        cp target/*.jar target/lambda/
        zip -j target/lambda.zip target/lambda/*

    - name: Test Lambda Package
      run: |
        if [ ! -f "target/lambda.zip" ]; then
          echo "Error: Lambda package not found!" >&2
          exit 1
        fi
        if [ ! -s "target/lambda.zip" ]; then
          echo "Error: Lambda package is empty!" >&2
          exit 1
        fi
        echo "Lambda package exists and is valid."

    - name: Upload to S3
      run: aws s3 cp target/lambda.zip s3://bucket-idpd-toinho/target/lambda.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ca-central-1
