name: Terraform CI/CD Debugging

on:
  workflow_dispatch: # Permite acionamento manual

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5

    - name: Plan Terraform with Debug
      working-directory: terraform
      env:
        TF_LOG: DEBUG
        TF_LOG_PATH: ./terraform-debug.log
      run: terraform plan -out=tfplan