name: Criar Infra CI/CD

on:
  workflow_dispatch: # Permite acionamento manual no GitHub Actions

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5

    - name: Debug AWS Credentials
      run: aws sts get-caller-identity
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ca-central-1

    - name: Initialize Terraform
      working-directory: terraform
      run: terraform init -reconfigure

    - name: Validate Terraform
      working-directory: terraform
      run: terraform validate

    - name: Plan Terraform
      working-directory: terraform
      run: terraform plan -out=tfplan

    - name: Apply Terraform
      working-directory: terraform
      run: terraform apply -auto-approve tfplan
